### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [Devdesiign/BuildCo#1]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by Devdesiign** [comment]
Hi, Code Hangen

This site is one of my test projects. 

Test project, I mean I built it to test my skills, It's not a really a Live product.

Many thanks,
DEVDESIIGNN.

**Comment by Devdesiign** [comment]
![Screenshot_20221228-060444.png](https://user-images.githubusercontent.com/57061186/209760391-b9bdf46b-3def-46ac-a264-94db6f1257df.png)

For context,

However, I'd love to connect with you if you don't mind?
